# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- feat/create-azurepipeline

pool:
  name: PoolRunners

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm run format
  displayName: 'npm format'

- script: |
    npm run lint
  displayName: 'npm lint'

- script: |
    npm run test
  displayName: 'npm test'
  
- script: |
    npm run test:cov
  displayName: 'npm test:cov'

- script: |
    npm run test:e2e
  displayName: 'npm test:e2e'

- script: |
    npm audit --audit-level=high
  displayName: 'npm audit'

- script: |
    npm ci
    npm run build
  displayName: 'npm install and build'


