version: '3.8'

services:
  nestjsazuredevops:
    image: nestjsazuredevops
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start:debug"]
    healthcheck:
      disable: true
